# Designed for OSX / Safari

def test_recordingSuite0():
    client = WindmillTestClient(__name__)

    client.click(link=u'sign in')
    client.waits.forPageLoad(timeout=u'20000')
    client.waits.forElement(timeout=u'8000', id=u'id_username')
    client.waits.forPageLoad(timeout=u'20000')
    client.click(id=u'id_username')
    client.waits.forPageLoad(timeout=u'20000')
    client.type(text=u'windmill', id=u'id_username')
    client.waits.forPageLoad(timeout=u'20000')
    client.click(id=u'id_password')
    client.waits.forPageLoad(timeout=u'20000')
    client.type(text=u'@mmap!', id=u'id_password')
    client.waits.forPageLoad(timeout=u'20000')
    client.click(xpath=u"//form[@id='auth_form']/fieldset/div[3]")
    client.waits.forPageLoad(timeout=u'20000')
    client.click(name=u'blogin')
    client.waits.forPageLoad(timeout=u'20000')
    client.waits.forElement(link=u'My Shapes', timeout=u'8000')
    client.waits.forPageLoad(timeout=u'20000')
    client.click(link=u'My Shapes')
    client.waits.forPageLoad(timeout=u'20000')
    client.click(xpath=u"//div[@id='sidebar']/ul/li[2]/a/span")
    client.waits.forPageLoad(timeout=u'20000')
    client.click(xpath=u"//li[@id='layers_menu']/span/a/img")
    client.waits.forPageLoad(timeout=u'20000')
